[workspace]
resolver = "2"
members = [
    "compiler/blyx_lexer",
    "compiler/blyx_parser",
    "compiler/blyx_ast",
    "compiler/blyx_semantic",
    "compiler/blyx_typeck",
    "compiler/blyx_bir",
    "compiler/blyxc",
    "library/blyx",
    "library/blyx-std",
    "tools/blyxpkg",
    "tools/blyxfmt",
    "tools/blyx-analyzer",
    "tools/blyxdoc",
    "tools/blyxup",
    "tools/blyxdbg",
    "tools/blyxprof",
]

[workspace.package]
version = "0.1.0-alpha"
edition = "2024"
authors = ["Rahul Chaube <rahulchaube1@gmail.com>", "Neuroblyx Core Team <contact@neuroblyx.com>"]
description = "Blyx: open-source AI-native systems programming language"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rahulchaube1/blyxxxx"
homepage = "https://blyx-lang.space"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
